version: "3.7"

networks:
  webphp:
    driver: bridge
    ipam:
      config:
        - subnet: 10.201.0.0/16
          gateway: 10.201.0.1
services:
    web:
        container_name: c-web
        platform: linux/amd64
        build: 
            context: ./
        ports:
            - 81:80
            - 443:443
        volumes:
            - ./code/html:/var/www/html
            - ./php/php.ini:/etc/php/8.1/fpm/php.ini
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./nginx/ssl:/etc/nginx/ssl
            - ./nginx/log/nginx:/var/log/nginx
            - ./php/supervisord.conf:/etc/supervisord.conf
        links:
            - mysql
            - redis
        healthcheck:
            test: ["CMD", "service", "nginx", "status"]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            webphp:
                ipv4_address: 10.201.0.2
    mysql: 
        build:
            context: ./mysql
            dockerfile: Dockerfile
        container_name: c-mysql
        command: [--default-authentication-plugin=mysql_native_password, --max-allowed-packet=10GB, --log_bin_trust_function_creators=1]
        ports: 
            - "3309:3306"
        restart: always
        volumes:
            - ./mysql/config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro
            - ./mysql/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=sample
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_USER=user
            - MYSQL_PASSWORD=123456
        healthcheck:
            test: mysqladmin ping
            interval: 3s
            timeout: 3s
            retries: 3
        networks:
            webphp:
                ipv4_address: 10.201.0.3
    redis:
        container_name: c-redis
        image: redis
        restart: always
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '6379:6379'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            webphp:
                ipv4_address: 10.201.0.4