version: "3.7"

networks:
  webphp:
    driver: bridge
    ipam:
      config:
        - subnet: 10.203.0.0/16
          gateway: 10.203.0.1
volumes:
  vendor:
    driver: local
  node_modules:
    driver: local
  mysql-database:
    driver: local
services:
  nginx:
    image: nginx:alpine
    container_name: gmo-nginx
    restart: unless-stopped
    ports:
      - 83:80
    volumes:
      - ./:/var/www/html:rw,cached
      - ./docker/nginx:/etc/nginx/conf.d/:ro
    links:
      - php
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      webphp:
        ipv4_address: 10.203.0.2
  php:
    build:
      args:
        user: root
      context: ./docker/php
      dockerfile: Dockerfile
    image: i-php
    container_name: gmo-php
    entrypoint: sh /bin/entrypoint.sh php-fpm
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:rw,cached
      - ./docker/build/entrypoint.sh:/bin/entrypoint.sh:ro
      - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      # Impove
      - "vendor:/var/www/html/vendor"
      - "node_modules:/var/www/html/node_modules"
    links:
      - db
      - redis
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      webphp:
        ipv4_address: 10.203.0.3
  db:
    image: mysql:8.0
    container_name: gmo-db
    restart: unless-stopped
    command: [--default-authentication-plugin=mysql_native_password, --max-allowed-packet=10GB, --log_bin_trust_function_creators=1]
    ports:
      - '3383:3306'
    environment:
      MYSQL_DATABASE: gmo
      MYSQL_ROOT_PASSWORD: Ka3%u6Ae
      MYSQL_USER: foo
      MYSQL_PASSWORD: hA*+BEAe
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d:ro
      # Impove
      - mysql-database:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      webphp:
        ipv4_address: 10.203.0.4
  redis:
    container_name: gmo-redis
    restart: unless-stopped
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6383:6379'
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      webphp:
        ipv4_address: 10.203.0.5